---
title: "Code (Combined Analysis)"
output: html_document
date: "2023-08-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Preprocessed Data

```{r}
unemp <- readr::read_csv(here::here('data/employment-processed.csv'))
rrpvote <- readr::read_csv(here::here('data/rrp-vote-processed.csv'))
```

## Join Data Sets

```{r}
df <- rrpvote %>%
  dplyr::inner_join(unemp, by = 'nuts2') %>%
  dplyr::select(
    country_code,
    nuts2,
    regionname,
    geometry = geometry.x,
    vote_share,
    emp2019
  )
```

## Export Combined Data

```{r}
readr::write_csv(x = df,
                 file = here::here('data/data-set.csv'))
```

## Analysis

```{r warning=FALSE}
ggplot(data = df,
       aes(x = emp2019, y = vote_share)) +
  geom_point(color = 'blue') +
  scale_y_continuous(breaks = c(0.1, 0.2, 0.3), labels = c(10, 20, 30)) +
  labs(title = 'Employment Rates of Citizens with Foreign Citizenship \nand Vote Shares of Nationalist and Radical Right Parties',
       x = 'Employment Rate in %',
       y = 'Vote Share in %') +
  geom_smooth(method = lm, color = 'orange')

ggsave(file = here::here('out/employment-voteshares.png'),
       width = 8, height = 4)
```
